### ISSUE TITLE
timeout on serial line

### ISSUE THREAD

**Issue by alisarikoc** [zsiki/ulyxes#39] opened 2021-05-23 17:16 UTC
I'm trying to test totalstation.py doc with `mu = LeicaTPS1200()` and using rs-232 cable connected to GEV267. But getting timeout error.

the error is on the line `ch = (self.ser.read(1)).decode('ascii')`

What should we set on the totalstation menu?

baudrate:9600
bytesize:8
stopbit:1
model: TCA1203

DEBUG:root: message sent: b'%R1Q,2009:\r\n'
ERROR:root: timeout on serial line

**Comment by zsiki** [comment] 2021-05-23 20:07
Which operating system are you using? Can you see serial port (COMn or /dev/ttyn or /dev/ttyUSBn) from the operating system? I've made a very short wiki page about it:
https://github.com/zsiki/ulyxes/wiki/Check-available-serial-line

**Comment by bkalafat** [comment] 2021-05-23 20:08
Windows but the issue is resolved by setting on total station.

**Closed as completed** 2021-05-23 23:13 UTC
